### ISSUE TITLE
Issue for Navmenu

### ISSUE THREAD

**Issue by cmakrionitis** [nauvalazhar/Magz#3]
hi Nauvalazhar thanks for theme, is great!!

I think, menu not work correctly for IOS device(Browser Chrome and Safari) but for Android work perfect.
Do you have any idea?

thanks again for your time!!!

**Comment by nauvalazhar** [comment]
Hi, thank you :)
I think it's about JavaScript event.
https://stackoverflow.com/questions/18914568/make-onclick-work-on-iphone

**Comment by cmakrionitis** [comment]
Thanks again, for your immediate answer nauvalazhar!!!
I think, solve my problem, with this [https://stackoverflow.com/questions/35945970/jquery-on-click-not-working-on-iphone-touch-devices](https://stackoverflow.com/questions/35945970/jquery-on-click-not-working-on-iphone-touch-devices)
